#!/bin/bash

IMAGE="pspdev-docker"

if [ "$(uname)" == "Linux" ] && [ -z "$(id|grep docker)" ] && [ "$EUID" -ne 0 ];then
	sudo "$0" "$@"
	exit $?
fi
if [ ! -z "$*" ]; then
  docker run -v "`pwd`:/build" --rm ${IMAGE} $*
else
  docker run -v "`pwd`:/build" --rm -it ${IMAGE} bash
fi
